title: "Jon Alejandro"
name: "Jon Alejandro"
description: "Power Management ICs | Semiconductor Strategy | System Power Architecture"
url: "https://jonalejandro.com"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Jon Alejandro"
  avatar: "https://avatars.githubusercontent.com/u/9439183?v=4"
  bio: "Product Line Manager in power management ICs and semiconductor strategy."
  location: "Dallas, TX"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jonalejandro"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jonalejandro"

header_pages:
  - _pages/about.md
  - _pages/notes.md
  - _pages/resume.md
  - _pages/contact.md
